2021-05-18 16:36:29.054 [192.168.42.226] [main] - [WARN ] [tk.mybatis.spring.mapper.ClassPathMapperScanner : 225] - Skipping MapperFactoryBean with name 'parkMapper' and 'ideal4j.robot.bigScreen.park.mapper.ParkMapper' mapperInterface. Bean already defined with the same name!
2021-05-18 16:36:29.059 [192.168.42.226] [main] - [WARN ] [tk.mybatis.spring.mapper.ClassPathMapperScanner : 225] - Skipping MapperFactoryBean with name 'safeProductionMapper' and 'ideal4j.robot.platform.interrobotface.safeProduction.mapper.SafeProductionMapper' mapperInterface. Bean already defined with the same name!
2021-05-18 16:36:29.059 [192.168.42.226] [main] - [WARN ] [tk.mybatis.spring.mapper.ClassPathMapperScanner : 142] - No MyBatis mapper was found in '[ideal4j.robot]' package. Please check your configuration.
2021-05-18 16:36:29.148 [192.168.42.226] [main] - [WARN ] [org.mybatis.spring.mapper.ClassPathMapperScanner : 239] - Skipping MapperFactoryBean with name 'parkMapper' and 'ideal4j.robot.bigScreen.park.mapper.ParkMapper' mapperInterface. Bean already defined with the same name!
2021-05-18 16:36:29.148 [192.168.42.226] [main] - [WARN ] [org.mybatis.spring.mapper.ClassPathMapperScanner : 239] - Skipping MapperFactoryBean with name 'safeProductionMapper' and 'ideal4j.robot.platform.interrobotface.safeProduction.mapper.SafeProductionMapper' mapperInterface. Bean already defined with the same name!
2021-05-18 16:36:29.149 [192.168.42.226] [main] - [WARN ] [org.mybatis.spring.mapper.ClassPathMapperScanner : 166] - No MyBatis mapper was found in '[ideal4j.robot]' package. Please check your configuration.
2021-05-18 16:36:52.313 [10.4.230.116] [main] - [WARN ] [o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext : 558] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: Invalid mapping on handler class [ideal4j.robot.platform.interrobotface.enterprise.action.EnterpriseServeAction]: public java.lang.String ideal4j.robot.platform.interrobotface.enterprise.action.EnterpriseServeAction.getData(java.lang.String)
2021-05-18 16:37:08.737 [10.4.230.116] [main] - [WARN ] [tk.mybatis.spring.mapper.ClassPathMapperScanner : 225] - Skipping MapperFactoryBean with name 'parkMapper' and 'ideal4j.robot.bigScreen.park.mapper.ParkMapper' mapperInterface. Bean already defined with the same name!
2021-05-18 16:37:08.738 [10.4.230.116] [main] - [WARN ] [tk.mybatis.spring.mapper.ClassPathMapperScanner : 225] - Skipping MapperFactoryBean with name 'safeProductionMapper' and 'ideal4j.robot.platform.interrobotface.safeProduction.mapper.SafeProductionMapper' mapperInterface. Bean already defined with the same name!
2021-05-18 16:37:08.738 [10.4.230.116] [main] - [WARN ] [tk.mybatis.spring.mapper.ClassPathMapperScanner : 142] - No MyBatis mapper was found in '[ideal4j.robot]' package. Please check your configuration.
2021-05-18 16:37:08.829 [10.4.230.116] [main] - [WARN ] [org.mybatis.spring.mapper.ClassPathMapperScanner : 239] - Skipping MapperFactoryBean with name 'parkMapper' and 'ideal4j.robot.bigScreen.park.mapper.ParkMapper' mapperInterface. Bean already defined with the same name!
2021-05-18 16:37:08.830 [10.4.230.116] [main] - [WARN ] [org.mybatis.spring.mapper.ClassPathMapperScanner : 239] - Skipping MapperFactoryBean with name 'safeProductionMapper' and 'ideal4j.robot.platform.interrobotface.safeProduction.mapper.SafeProductionMapper' mapperInterface. Bean already defined with the same name!
2021-05-18 16:37:08.831 [10.4.230.116] [main] - [WARN ] [org.mybatis.spring.mapper.ClassPathMapperScanner : 166] - No MyBatis mapper was found in '[ideal4j.robot]' package. Please check your configuration.
2021-05-18 16:37:18.051 [10.4.230.116] [main] - [WARN ] [o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext : 558] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: Invalid mapping on handler class [ideal4j.robot.platform.interrobotface.enterprise.action.EnterpriseServeAction]: public java.lang.String ideal4j.robot.platform.interrobotface.enterprise.action.EnterpriseServeAction.getData(java.lang.String)
2021-05-18 16:38:04.091 [10.4.230.116] [main] - [WARN ] [tk.mybatis.spring.mapper.ClassPathMapperScanner : 225] - Skipping MapperFactoryBean with name 'parkMapper' and 'ideal4j.robot.bigScreen.park.mapper.ParkMapper' mapperInterface. Bean already defined with the same name!
2021-05-18 16:38:04.092 [10.4.230.116] [main] - [WARN ] [tk.mybatis.spring.mapper.ClassPathMapperScanner : 225] - Skipping MapperFactoryBean with name 'safeProductionMapper' and 'ideal4j.robot.platform.interrobotface.safeProduction.mapper.SafeProductionMapper' mapperInterface. Bean already defined with the same name!
2021-05-18 16:38:04.093 [10.4.230.116] [main] - [WARN ] [tk.mybatis.spring.mapper.ClassPathMapperScanner : 142] - No MyBatis mapper was found in '[ideal4j.robot]' package. Please check your configuration.
2021-05-18 16:38:04.182 [10.4.230.116] [main] - [WARN ] [org.mybatis.spring.mapper.ClassPathMapperScanner : 239] - Skipping MapperFactoryBean with name 'parkMapper' and 'ideal4j.robot.bigScreen.park.mapper.ParkMapper' mapperInterface. Bean already defined with the same name!
2021-05-18 16:38:04.183 [10.4.230.116] [main] - [WARN ] [org.mybatis.spring.mapper.ClassPathMapperScanner : 239] - Skipping MapperFactoryBean with name 'safeProductionMapper' and 'ideal4j.robot.platform.interrobotface.safeProduction.mapper.SafeProductionMapper' mapperInterface. Bean already defined with the same name!
2021-05-18 16:38:04.184 [10.4.230.116] [main] - [WARN ] [org.mybatis.spring.mapper.ClassPathMapperScanner : 166] - No MyBatis mapper was found in '[ideal4j.robot]' package. Please check your configuration.
2021-05-18 17:19:21.452 [127.0.0.1] [lettuce-eventExecutorLoop-1-1] - [WARN ] [io.lettuce.core.protocol.ConnectionWatchdog : 105] - Cannot reconnect to [172.31.47.176:6379]: No route to host: no further information: /172.31.47.176:6379
io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: no further information: /172.31.47.176:6379
Caused by: java.net.NoRouteToHostException: No route to host: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2021-05-18 17:19:21.452 [127.0.0.1] [lettuce-eventExecutorLoop-1-8] - [WARN ] [io.lettuce.core.protocol.ConnectionWatchdog : 105] - Cannot reconnect to [172.31.47.176:6379]: No route to host: no further information: /172.31.47.176:6379
io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: no further information: /172.31.47.176:6379
Caused by: java.net.NoRouteToHostException: No route to host: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2021-05-18 18:09:21.246 [127.0.0.1] [lettuce-nioEventLoop-4-7] - [WARN ] [io.lettuce.core.protocol.ConnectionWatchdog : 105] - Cannot reconnect to [172.31.47.176:6379]: No route to host: no further information: /172.31.47.176:6379
io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: no further information: /172.31.47.176:6379
Caused by: java.net.NoRouteToHostException: No route to host: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2021-05-18 18:09:21.245 [127.0.0.1] [lettuce-nioEventLoop-4-8] - [WARN ] [io.lettuce.core.protocol.ConnectionWatchdog : 105] - Cannot reconnect to [172.31.47.176:6379]: No route to host: no further information: /172.31.47.176:6379
io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: no further information: /172.31.47.176:6379
Caused by: java.net.NoRouteToHostException: No route to host: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2021-05-18 21:09:22.505 [127.0.0.1] [lettuce-nioEventLoop-4-5] - [WARN ] [io.lettuce.core.protocol.ConnectionWatchdog : 105] - Cannot reconnect to [172.31.47.176:6379]: No route to host: no further information: /172.31.47.176:6379
io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: no further information: /172.31.47.176:6379
Caused by: java.net.NoRouteToHostException: No route to host: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2021-05-18 21:09:22.518 [127.0.0.1] [lettuce-nioEventLoop-4-6] - [WARN ] [io.lettuce.core.protocol.ConnectionWatchdog : 105] - Cannot reconnect to [172.31.47.176:6379]: No route to host: no further information: /172.31.47.176:6379
io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: no further information: /172.31.47.176:6379
Caused by: java.net.NoRouteToHostException: No route to host: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
